name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "🎉 Welcome to the project! Thank you for opening an issue. Your input is valuable, and we appreciate your time in helping us improve. We'll get back to you as soon as possible!"
        pr-message: "🚀 Thanks for your first pull request! We're excited to see your contribution and will review it shortly. Your efforts help make this project better, and we're grateful to have you involved!"
